### ISSUE TITLE
Dot env isnt ebing installed?

### ISSUE THREAD

**Issue by johnrraymond** [GtLibrary/thegreatlibrary#36]
:/home/john/bakerydemo/moralis$ node secure-backend.js 9999 127.0.0.1 127.0.0.1
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/john/thegreatlibrary/moralis/tools.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by Ken-tech-max** [comment]
I recommend you to execute this command in cli.
`npm i dotenv`
